# -*- coding: utf-8 -*-
"""W1D4Daily.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISWOeZLmAR1LLmMFEpr7aPRUbxWieCmf
"""

# Coffee Shop Menu Manager

# Initial data
menu = {
    "espresso": 7.0,
    "latte": 12.0,
    "cappuccino": 10.0
}

def show_menu(menu_dict):
    """Print all drinks and prices."""
    if not menu_dict:
        print("The menu is empty.")
    else:
        print("Current menu:")
        for drink, price in menu_dict.items():
            print(f"{drink} - {price}₪")


def add_item(menu_dict):
    """Add a new drink to the menu."""
    drink_name = input("Enter new drink name: ").strip()
    if drink_name in menu_dict:
        print("Item already exists!")
        return

    price_input = input("Enter price: ").strip()
    try:
        price = float(price_input)
    except ValueError:
        print("Invalid price.")
        return

    menu_dict[drink_name] = price
    print(f"\"{drink_name}\" added!")


def update_price(menu_dict):
    """Change the price of an existing drink."""
    drink_name = input("Which drink do you want to update? ").strip()
    if drink_name not in menu_dict:
        print("Item not found.")
        return

    price_input = input("Enter the new price: ").strip()
    try:
        new_price = float(price_input)
    except ValueError:
        print("Invalid price.")
        return

    menu_dict[drink_name] = new_price
    print("Price updated!")


def delete_item(menu_dict):
    """Remove a drink from the menu."""
    drink_name = input("Which drink do you want to delete? ").strip()
    if drink_name in menu_dict:
        del menu_dict[drink_name]
        print("Item deleted!")
    else:
        print("Item not found.")


def show_options():
    """Print the available actions."""
    print("What would you like to do?")
    print("1. Show menu")
    print("2. Add item")
    print("3. Update price")
    print("4. Delete item")
    print("5. Exit")


def run_coffee_shop():
    """Main loop of the program."""
    while True:
        show_options()
        choice = input("> ").strip()

        if choice == "1":
            show_menu(menu)
        elif choice == "2":
            add_item(menu)
        elif choice == "3":
            update_price(menu)
        elif choice == "4":
            delete_item(menu)
        elif choice == "5":
            print("Goodbye!")
            break
        else:
            print("Invalid choice, try again.")


# Start the program
run_coffee_shop()