# -*- coding: utf-8 -*-
"""W2D5Daily1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VG6YjgLpYETXSJRtU3iMe3Sqq6CfnOCR

Exercise 1: Quiz Answers

1. What is a class?
A class is a blueprint for creating objects. It defines attributes and methods.

2. What is an instance?
An instance is a specific object created from a class.

3. What is encapsulation?
Encapsulation hides internal data by restricting direct access and controlling it through methods.

4. What is abstraction?
Abstraction hides unnecessary implementation details and exposes only essential features.

5. What is inheritance?
Inheritance allows one class (child) to receive attributes and methods from another class (parent).

6. What is multiple inheritance?
Multiple inheritance means a class can inherit from more than one parent class.

7. What is polymorphism?
Polymorphism allows methods with the same name to behave differently depending on the object.

8. What is Method Resolution Order (MRO)?
MRO defines the order in which Python looks for methods/attributes in inheritance chains.
"""