# -*- coding: utf-8 -*-
"""W2D5Daily2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0n_8K-muR4Akk-J-chjgP5r2hnHWIT9
"""

import random

class Card:
    def __init__(self, suit, value):
        self.suit = suit
        self.value = value

    def __repr__(self):
        return f"{self.value} of {self.suit}"


class Deck:
    suits = ["Hearts", "Diamonds", "Clubs", "Spades"]
    values = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"]

    def __init__(self):
        self.cards = []

    def shuffle(self):
        """Create all 52 cards and shuffle them."""
        self.cards = [Card(suit, value) for suit in Deck.suits for value in Deck.values]
        random.shuffle(self.cards)

    def deal(self):
        """Deal one card and remove it from the deck."""
        if not self.cards:
            return "No cards left in the deck!"
        return self.cards.pop()