# -*- coding: utf-8 -*-
"""W2D5Mini2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXUwrJvHWuG82moAKnad0qxuWc5pP5hJ
"""

from game import Game


def get_user_menu_choice():
    """
    Show the menu and ask the user for a choice.
    Valid options:
        1 - Play a new game
        2 - Show scores
        q - Quit
    Return the user's choice as a string.
    """
    print("=== Rock Paper Scissors ===")
    print("1. Play a new game")
    print("2. Show scores")
    print("q. Quit")

    while True:
        choice = input("Enter your choice (1/2/q): ").strip().lower()
        if choice in ["1", "2", "q"]:
            return choice
        else:
            print("Invalid choice, please enter 1, 2 or q.\n")


def print_results(results):
    """
    Print the game summary.
    results is a dict like: {"win": 2, "loss": 4, "draw": 3}
    """
    wins = results.get("win", 0)
    losses = results.get("loss", 0)
    draws = results.get("draw", 0)

    print("\n=== Game Results ===")
    print(f"Wins:   {wins}")
    print(f"Losses: {losses}")
    print(f"Draws:  {draws}")
    print("\nThanks for playing! 👋\n")


def main():
    results = {"win": 0, "loss": 0, "draw": 0}

    while True:
        choice = get_user_menu_choice()

        if choice == "1":
            # Play a new game
            game = Game()
            result = game.play()
            # Update scores
            if result in results:
                results[result] += 1

        elif choice == "2":
            # Show current scores
            print_results(results)

        elif choice == "q":
            # Quit and show final summary
            print_results(results)
            break


if __name__ == "__main__":
    main()