# -*- coding: utf-8 -*-
"""W2D5Daily1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iR5DX0A7wIv1etfM7L7CR9B9Ad_Ou_wI
"""

import random


class Game:
    def __init__(self):
        # You can add attributes later if needed
        self.valid_items = ["rock", "paper", "scissors"]

    def get_user_item(self):
        """
        Ask the user to choose rock, paper or scissors.
        Keep asking until the user gives a valid input.
        Return the chosen item as a string.
        """
        while True:
            user_input = input("Choose [r]ock, [p]aper or [s]cissors: ").strip().lower()

            # Allow both short and full forms
            if user_input in ["r", "rock"]:
                return "rock"
            elif user_input in ["p", "paper"]:
                return "paper"
            elif user_input in ["s", "scissors"]:
                return "scissors"
            else:
                print("Invalid choice, please try again.\n")

    def get_computer_item(self):
        """
        Randomly select rock, paper or scissors for the computer.
        Return the chosen item as a string.
        """
        return random.choice(self.valid_items)

    def get_game_result(self, user_item, computer_item):
        """
        Determine the game result.
        Return one of: "win", "loss", "draw".
        """
        if user_item == computer_item:
            return "draw"

        # Winning combinations for the user
        winning_combos = {
            "rock": "scissors",
            "paper": "rock",
            "scissors": "paper"
        }

        if winning_combos[user_item] == computer_item:
            return "win"
        else:
            return "loss"

    def play(self):
        """
        Run one round of the game:
        - get the user's choice
        - get the computer's choice
        - determine and print the result
        - return "win", "loss" or "draw"
        """
        user_item = self.get_user_item()
        computer_item = self.get_computer_item()
        result = self.get_game_result(user_item, computer_item)

        print(f"\nYou chose:     {user_item}")
        print(f"Computer chose: {computer_item}")

        if result == "win":
            print("Result: You WIN! 🎉")
        elif result == "loss":
            print("Result: You LOSE! 😢")
        else:
            print("Result: It's a DRAW 😐")

        print()  # blank line for readability
        return result